### ISSUE TITLE
how to use this awesome tool

### ISSUE THREAD

**Issue by baifengbai** [absop/ChineseTokenizer#1]

**Comment by absop** [comment]
I will write a README，Tomorrow.

**Comment by baifengbai** [comment]
老哥geilivable！有没有介绍这些sublime插件开发过程的文章供学习一下

**Comment by absop** [comment]
> 老哥geilivable！有没有介绍这些sublime插件开发过程的文章供学习一下


嗯，如果会Python的话，可以找个SublimeText插件的源码参考一下，另外认真看一下SublimeText 安装目录下的两个Python文件：`sublime.py` 和 `sublime_plugin.py`。然后文档的话，SublimeText官网有。

**Comment by baifengbai** [comment]
好的谢谢

**Comment by absop** [comment]
> 好的谢谢
我写的在Sublime里面运行的带有彩色界面的2048小游戏，可以参考一下喔😂

https://github.com/absop/Sublime2048
