### ISSUE TITLE
建议明确安装步骤

### ISSUE THREAD

**Issue by chirsz-ever** [absop/ChineseTokenizer#3]
感谢开发这个插件！

希望在 README 里作出更明确的安装指示，也就是说复制到 `Packages` 文件夹：

> By default, the Packages directories for Sublime Text 2 are located at:
>
>   - OS X: `~/Library/Application Support/Sublime Text 2/Packages/`
>   - Windows: `%APPDATA%/Roaming/Sublime Text 2/Packages/`
>   - Linux: `~/.config/sublime-text-2/Packages/`
> 
> By default, the Packages directories for Sublime Text 3 are located at:
> 
>   - OS X: `~/Library/Application Support/Sublime Text 3/Packages/`
>   - Windows: `%APPDATA%/Roaming/Sublime Text 3/Packages/`
>   - Linux: `~/.config/sublime-text-3/Packages/`
> 

希望将此插件加入 Package Control。

**Comment by absop** [comment]
> 感谢开发这个插件！
> 
> 希望在 README 里作出更明确的安装指示，也就是说复制到 `Packages` 文件夹：
> 
> > By default, the Packages directories for Sublime Text 2 are located at:
> > 
> > * OS X: `~/Library/Application Support/Sublime Text 2/Packages/`
> > * Windows: `%APPDATA%/Roaming/Sublime Text 2/Packages/`
> > * Linux: `~/.config/sublime-text-2/Packages/`
> > 
> > By default, the Packages directories for Sublime Text 3 are located at:
> > 
> > * OS X: `~/Library/Application Support/Sublime Text 3/Packages/`
> > * Windows: `%APPDATA%/Roaming/Sublime Text 3/Packages/`
> > * Linux: `~/.config/sublime-text-3/Packages/`
> 
> 希望将此插件加入 Package Control。

谢谢你。

我已经在Package Control的仓库提交了PR，等待merging。
等merge之后我就把安装方法贴在`README`中 。

**Comment by absop** [comment]
我在`Package Control`中把插件的名字改了，新名字是`Chinese Words Cutter`，不过仓库依然是这个。

**Comment by absop** [comment]
@ykqmain Thanks for improving the README.md file.
